name: Auditoria

on: [push]

jobs:
  verificacao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar Pandas
        run: pip install pandas
      - name: Rodar Auditoria
        run: python scripts/auditoria_automatizada.py
